mysql:
  container_name: mariadb_aula
  image: mariadb:10.4.14
  ports:
      - 3306:3306
  environment: 
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=auladb
  command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0